#!/bin/sh
#
# Copyright 2013 The Imaging Source Europe GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# this assumes you have a local installation of aravis
# if this is not the case simply adjust these variables to point to the concerning directories,
# if they are not already in your established search path

# set this to your aravis path
export ARV_HOME=/home/*/work/aravis

# adjust gobject introspection search path to find the file Aravis-0.4.gir
export GI_TYPELIB_PATH=$GI_TYPELIB_PATH:$ARV_HOME/src

# adjust runtime path for shared libraries to find libaravis-0.4.so
export LD_LIBRARY_PATH=$ARV_HOME/src/.libs

# starts example script
python $*

