
* video4linux

** identifying your device

   To identify your device you have several methods

   - udev
   - /dev

   To reliably identify your device, use the directory '/dev/v4l/by-id/'.
   There you will find a softlink that reliably identifies your device in a unique manner.

   Example:
       ls /dev/v4l/by-id

       usb-The_Imaging_Source_Europe_GmbH_DFK_23U618_50419999-video-index0

* aravis

* gstreamer

** useful modules

   This is a list of modules not provided by the Imaging Source that you may find helpful.
   All mentioned modules are part of the debian standard repositories.

* useful tools

** wireshark

*** monitoring usb

To monitor usb, execute the following command.

    sudo modprobe usbmon

This loads kernel modules that allow usb monitoring.

When opening the device that shall be monitored, select the bus the camera is
connected to.

This can be found with

    lsusb -t

* Misc

** Reducing disk I/O

When regularly writing imagas to disk it can be advisable to reduce to write
process to a minimum (especially when working with systems like a raspberry pi).

This can be done by moving the directory that shall be written to into a
temporary filesystem (tmpfs) that resides in memory.

Be aware that on a reboot of the system all data stored in a tmpfs will be lost.
