FIND_PATH(AUDIT_INCLUDE_DIR libaudit.h /usr/include
    /usr/local/include)

FIND_LIBRARY(AUDIT_LIBRARY NAMES libaudit.a PATH /usr/lib /usr/local/lib) 

IF (AUDIT_INCLUDE_DIR AND AUDIT_LIBRARY)
   SET(AUDIT_FOUND TRUE)
ENDIF (AUDIT_INCLUDE_DIR AND AUDIT_LIBRARY)


IF (AUDIT_FOUND)
   IF (NOT audit_FIND_QUIETLY)
      MESSAGE(STATUS "Found audit: ${AUDIT_LIBRARY}")
   ENDIF (NOT audit_FIND_QUIETLY)
ELSE (AUDIT_FOUND)
   IF (audit_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find audit")
   ENDIF (audit_FIND_REQUIRED)
ENDIF (AUDIT_FOUND)
